name: Cicd
on:
  push:
  branches: ["main"]
  jobs:
  build:
  runs-on: ubuntu-latest
  strategy:
  matrix:
  node-version: [14.x, 16.x, 18.x]
  steps:
  uses: action/checkout@v3
  name: Use Node.js ${{ matrix.node-version}}
  uses: action/set-up@v3
  with:
  node-version: ${{ matrix.node-version}}
  cache: npm
  run: npm install
  run: npm run build --if-present
  run: npm run test --if-present
  
  
